use anyhow::{bail, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::archive;

pub const DESKTOP_FILE: &str = "aseprite-compiler.aseprite.desktop";
pub const ICON_NAME: &str = "aseprite-compiler-aseprite";

pub fn aseprite_bin(install_root: &Path) -> PathBuf {
    install_root
        .join("current")
        .join(if cfg!(windows) { "aseprite.exe" } else { "aseprite" })
}

/// Heal an interrupted install transaction. Called at app startup and before
/// every install:
/// - `current` missing but `.previous` present (crash between the two
///   renames) → restore the previous working build;
/// - `current` and `.previous` both present (crash after activation) → the
///   activated build was already validated, so the leftover can go;
/// - stray `.staging` with no active transaction → remove it.
pub fn recover_install(install_root: &Path) {
    let current = install_root.join("current");
    let previous = install_root.join(".previous");
    let staging = install_root.join(".staging");

    if !current.exists() && previous.exists() {
        let _ = fs::rename(&previous, &current);
    } else if current.exists() && previous.exists() {
        fs::remove_dir_all(&previous).ok();
    }
    fs::remove_dir_all(&staging).ok();
}

/// Copy the finished build (aseprite binary + data folder) into the install
/// root transactionally: stage, validate the staged binary, then swap —
/// restoring the old build on failure. The previous build is only removed
/// after the new one is active. Returns (installed bytes, validated version).
pub fn install_build(
    build_bin_dir: &Path,
    install_root: &Path,
    validate: impl Fn(&Path) -> Result<String>,
) -> Result<(u64, String)> {
    let bin_name = if cfg!(windows) { "aseprite.exe" } else { "aseprite" };
    if !build_bin_dir.join(bin_name).is_file() {
        bail!(
            "build output not found at {}",
            build_bin_dir.join(bin_name).display()
        );
    }

    fs::create_dir_all(install_root)?;
    let staging = install_root.join(".staging");
    let current = install_root.join("current");
    let old = install_root.join(".previous");

    fs::remove_dir_all(&staging).ok();
    let mut installed_bytes =
        archive::copy_tree(build_bin_dir, &staging).context("staging new build")?;

    // The build's internal code-generator tool isn't part of Aseprite.
    for tool in ["gen", "gen.exe"] {
        let p = staging.join(tool);
        if let Ok(meta) = fs::metadata(&p) {
            installed_bytes = installed_bytes.saturating_sub(meta.len());
            fs::remove_file(&p).ok();
        }
    }
    if !staging.join("data").is_dir() {
        fs::remove_dir_all(&staging).ok();
        bail!("staged build is missing its data directory");
    }

    // Validate the staged binary BEFORE touching the working install.
    let version = match validate(&staging.join(bin_name)) {
        Ok(v) => v,
        Err(e) => {
            fs::remove_dir_all(&staging).ok();
            return Err(e).context("validating the staged build");
        }
    };

    // recover_install ran before us, so .previous should not exist; the
    // defensive removal only clears debris, never a needed rollback copy.
    fs::remove_dir_all(&old).ok();
    let had_current = current.exists();
    if had_current {
        fs::rename(&current, &old).context("moving previous build aside")?;
    }
    if let Err(e) = fs::rename(&staging, &current) {
        // Roll back so the previous install keeps working.
        if had_current {
            let _ = fs::rename(&old, &current);
        }
        return Err(e).context("activating new build");
    }
    fs::remove_dir_all(&old).ok();
    Ok((installed_bytes, version))
}

/// The app path Aseprite's launcher entry should go through when the
/// launch-check shim is enabled: None when disabled or unknown.
pub fn shim_path() -> Option<PathBuf> {
    if !crate::settings::Settings::load().check_on_launch {
        return None;
    }
    crate::paths::app_executable()
}

/// Write the launcher wrapper next to the install. The OS launcher entry
/// points at this wrapper instead of this app's executable, so Aseprite
/// keeps launching — directly, with no update check — even when this app
/// has been moved or uninstalled and never got a chance to repair the entry.
#[allow(unused_variables)]
fn write_wrapper(install_root: &Path, shim: Option<&Path>) -> Result<PathBuf> {
    let bin = aseprite_bin(install_root);

    #[cfg(target_os = "linux")]
    {
        // Single-quoted shell literals: ' becomes '\'' so paths can't break out.
        let sq = |p: &Path| p.display().to_string().replace('\'', "'\\''");
        let path = install_root.join("launch.sh");
        let app = shim.map(sq).unwrap_or_default();
        let script = format!(
            "#!/bin/sh\n\
             # Generated by Aseprite Compiler. Starts Aseprite through the\n\
             # compiler app (quiet update check) when it is available, and\n\
             # directly otherwise.\n\
             APP='{app}'\n\
             BIN='{bin}'\n\
             if [ -n \"$APP\" ] && [ -x \"$APP\" ]; then\n\
                 exec \"$APP\" --run-aseprite \"$@\"\n\
             fi\n\
             exec \"$BIN\" \"$@\"\n",
            bin = sq(&bin),
        );
        if fs::read_to_string(&path).ok().as_deref() != Some(script.as_str()) {
            fs::write(&path, script)?;
        }
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755))?;
        return Ok(path);
    }

    #[cfg(target_os = "windows")]
    {
        // Windows paths cannot contain double quotes, so plain embedding is safe.
        let path = install_root.join("launch.vbs");
        let app = shim.map(|p| p.display().to_string()).unwrap_or_default();
        let script = format!(
            "' Generated by Aseprite Compiler. Starts Aseprite through the\r\n\
             ' compiler app (quiet update check) when it is available, and\r\n\
             ' directly otherwise.\r\n\
             Set fso = CreateObject(\"Scripting.FileSystemObject\")\r\n\
             Set sh = CreateObject(\"WScript.Shell\")\r\n\
             app = \"{app}\"\r\n\
             bin = \"{bin}\"\r\n\
             If Len(app) > 0 Then\r\n\
                 If fso.FileExists(app) Then\r\n\
                     sh.Run \"\"\"\" & app & \"\"\" --run-aseprite\", 0, False\r\n\
                     WScript.Quit\r\n\
                 End If\r\n\
             End If\r\n\
             sh.Run \"\"\"\" & bin & \"\"\"\", 1, False\r\n",
            bin = bin.display(),
        );
        if fs::read_to_string(&path).ok().as_deref() != Some(script.as_str()) {
            fs::write(&path, script)?;
        }
        return Ok(path);
    }

    #[cfg(not(any(target_os = "linux", target_os = "windows")))]
    {
        Ok(bin)
    }
}

/// Register the compiled Aseprite in the OS application launcher.
/// `src_root` is the extracted Aseprite source tree (for the icons).
pub fn register_launcher(install_root: &Path, src_root: &Path) -> Result<()> {
    #[cfg(target_os = "linux")]
    {
        let data_home = dirs::data_dir().context("no data dir")?;
        // Icons from the Aseprite source tree into the hicolor theme.
        let icon_src = src_root.join("data").join("icons");
        for size in [16u32, 32, 48, 64, 128, 256] {
            let candidate = icon_src.join(format!("ase{size}.png"));
            if candidate.is_file() {
                let dir = data_home
                    .join("icons/hicolor")
                    .join(format!("{size}x{size}"))
                    .join("apps");
                fs::create_dir_all(&dir)?;
                fs::copy(&candidate, dir.join(format!("{ICON_NAME}.png")))?;
            }
        }
        let _ = std::process::Command::new("gtk-update-icon-cache")
            .args(["-q", "-t"])
            .arg(data_home.join("icons/hicolor"))
            .status();
    }
    #[cfg(not(target_os = "linux"))]
    let _ = src_root;

    write_launcher_entry(install_root, shim_path().as_deref())
}

/// (Re)write Aseprite's launcher entry so it matches current reality. Called
/// after an install, when the launch-check setting changes, and at every app
/// start — which self-repairs the entry if this app's executable moved
/// (e.g. a relocated AppImage that the entry's shim Exec pointed at).
pub fn write_launcher_entry(install_root: &Path, shim: Option<&Path>) -> Result<()> {
    let bin = aseprite_bin(install_root);
    let wrapper = write_wrapper(install_root, shim)?;

    #[cfg(target_os = "linux")]
    {
        let data_home = dirs::data_dir().context("no data dir")?;
        let apps_dir = data_home.join("applications");
        fs::create_dir_all(&apps_dir)?;
        let icon_ok = data_home
            .join("icons/hicolor/64x64/apps")
            .join(format!("{ICON_NAME}.png"))
            .is_file();
        let exec = format!("\"{}\" %U", wrapper.display());
        let desktop = format!(
            "[Desktop Entry]\n\
             Type=Application\n\
             Name=Aseprite\n\
             Comment=Animated sprite editor & pixel art tool (local build)\n\
             TryExec={bin}\n\
             Exec={exec}\n\
             Icon={icon}\n\
             Terminal=false\n\
             Categories=Graphics;2DGraphics;RasterGraphics;\n\
             MimeType=image/x-aseprite;\n\
             StartupWMClass=Aseprite\n",
            bin = bin.display(),
            icon = if icon_ok { ICON_NAME } else { "image-x-generic" },
        );
        let path = apps_dir.join(DESKTOP_FILE);
        // Rewrite (and poke the launcher caches) only when something changed.
        if fs::read_to_string(&path).ok().as_deref() != Some(desktop.as_str()) {
            fs::write(&path, desktop)?;
            let _ = std::process::Command::new("update-desktop-database")
                .arg(&apps_dir)
                .status();
        }
        Ok(())
    }

    #[cfg(target_os = "windows")]
    {
        let appdata = std::env::var("APPDATA").context("no APPDATA")?;
        let lnk = Path::new(&appdata)
            .join("Microsoft\\Windows\\Start Menu\\Programs\\Aseprite (local build).lnk");
        // The shortcut runs the wrapper hidden via wscript; the wrapper picks
        // shim vs. direct launch at click time.
        let system_root = std::env::var("SystemRoot").unwrap_or_else(|_| "C:\\Windows".into());
        let target = Path::new(&system_root).join("System32\\wscript.exe");
        let args = format!("//B \"{}\"", wrapper.display());
        // Single-quoted PowerShell literals escape ' by doubling it — a path
        // containing an apostrophe (e.g. C:\Users\O'Brien) must not break out.
        let ps = |s: String| s.replace('\'', "''");
        let script = format!(
            "$ws = New-Object -ComObject WScript.Shell; \
             $s = $ws.CreateShortcut('{lnk}'); \
             $s.TargetPath = '{target}'; \
             $s.Arguments = '{args}'; \
             $s.WorkingDirectory = '{dir}'; \
             $s.IconLocation = '{bin},0'; \
             $s.Description = 'Aseprite (compiled locally)'; \
             $s.Save()",
            lnk = ps(lnk.display().to_string()),
            target = ps(target.display().to_string()),
            args = ps(args),
            bin = ps(bin.display().to_string()),
            dir = ps(bin.parent().unwrap().display().to_string()),
        );
        let status = std::process::Command::new("powershell")
            .args(["-NoProfile", "-NonInteractive", "-Command", &script])
            .status()
            .context("running powershell to create Start Menu shortcut")?;
        if !status.success() {
            bail!("could not create the Start Menu shortcut");
        }
        Ok(())
    }

    #[cfg(not(any(target_os = "linux", target_os = "windows")))]
    {
        let _ = (bin, shim, wrapper);
        Ok(())
    }
}

/// Startup self-repair: if Aseprite is installed, make sure its launcher
/// entry exists and points at live paths (fixes a moved AppImage/executable).
pub fn repair_launcher_entry() {
    let root = crate::updates::install_root();
    if !aseprite_bin(&root).is_file() {
        return;
    }
    let _ = write_launcher_entry(&root, shim_path().as_deref());
}

/// Remove the installed build and its launcher entry. Aseprite's own
/// preferences and user files are untouched.
pub fn uninstall(install_root: &Path) -> Result<()> {
    fs::remove_dir_all(install_root.join("current")).ok();
    fs::remove_dir_all(install_root.join(".staging")).ok();
    fs::remove_dir_all(install_root.join(".previous")).ok();
    fs::remove_file(install_root.join("launch.sh")).ok();
    fs::remove_file(install_root.join("launch.vbs")).ok();
    fs::remove_dir(install_root).ok(); // only if now empty

    #[cfg(target_os = "linux")]
    {
        if let Some(data_home) = dirs::data_dir() {
            fs::remove_file(data_home.join("applications").join(DESKTOP_FILE)).ok();
            for size in [16u32, 32, 48, 64, 128, 256] {
                fs::remove_file(
                    data_home
                        .join("icons/hicolor")
                        .join(format!("{size}x{size}"))
                        .join("apps")
                        .join(format!("{ICON_NAME}.png")),
                )
                .ok();
            }
            let _ = std::process::Command::new("update-desktop-database")
                .arg(data_home.join("applications"))
                .status();
        }
    }

    #[cfg(target_os = "windows")]
    {
        if let Ok(appdata) = std::env::var("APPDATA") {
            fs::remove_file(
                Path::new(&appdata)
                    .join("Microsoft\\Windows\\Start Menu\\Programs\\Aseprite (local build).lnk"),
            )
            .ok();
        }
    }

    Ok(())
}
